[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/dlsteuer/miniredis"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.10.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"
